FROM      mariobyn/debian:java8

USER root

ENV DEBIAN_FRONTEND noninteractive

RUN wget https://download.elasticsearch.org/logstash/logstash/logstash-1.5.0.tar.gz -O /tmp/logstash.tar.gz 2> /dev/null

RUN tar zxvf /tmp/logstash.tar.gz -C /opt && mv /opt/logstash-1.5.0 /opt/logstash && rm -rf /tmp/logstash.tar.gz

ADD start_logstash.sh /usr/local/bin/start_logstash.sh
RUN chmod +x /usr/local/bin/start_logstash.sh

RUN mkdir /opt/logs

ADD collectd-types.db /opt/collectd-types.db

VOLUME ["/opt/conf", "/opt/certs", "/opt/logs"]

EXPOSE 514
EXPOSE 5043
EXPOSE 9292

#CMD /usr/local/bin/start_logstash.sh
CMD bash